package org.example.service;


import lombok.AllArgsConstructor;

import org.example.entities.UserInfo;
import org.example.eventProducer.UserInfoProducer;
import org.example.model.UserInfoDto;
import org.example.repos.UserRepo;
import org.example.request.UserRegistrationRequest;
import org.example.utils.ValidateUserUtil;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.crypto.password.PasswordEncoder;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;



@Service
@AllArgsConstructor
public class UserDetailsImpl implements UserDetailsService {

    private final UserRepo userRepo;
    private final PasswordEncoder passwordEncoder;
    private final UserInfoProducer userInfoProducer;

    @Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
        return userRepo.findByUserName(username)
                .orElseThrow(() -> new UsernameNotFoundException("User not found: " + username));
    }

    @Transactional
    public Boolean signUpUser(UserRegistrationRequest registrationRequest) {
        // 1. Validation Logic
        if (!ValidateUserUtil.isValidUser(registrationRequest.getEmail(), registrationRequest.getPassword())) {
            return false;
        }

        // 2. Duplicate Check
        if (userRepo.findByUserName(registrationRequest.getUserName()).isPresent()) {
            return false;
        }

        // 3. Entity Preparation
        UserInfo userEntity = new UserInfo();
        userEntity.setUsername(registrationRequest.getUserName());
        userEntity.setEmail(registrationRequest.getEmail());
        userEntity.setPassword(passwordEncoder.encode(registrationRequest.getPassword()));

        // 4. Save to Auth DB (UUID generated by @UuidGenerator)
        UserInfo savedUser = userRepo.save(userEntity);

        // 5. Convert to UserInfoDto for Kafka (NO PASSWORD)
        UserInfoDto kafkaEventData = UserInfoDto.builder()
                .userId(savedUser.getUserId())
                .userName(savedUser.getUsername())
                .email(savedUser.getEmail())
                .firstName(registrationRequest.getFirstName())
                .lastName(registrationRequest.getLastName())
                .phoneNumber(registrationRequest.getPhoneNumber())
                .build();

        // 6. Sync via Kafka
        try {
            userInfoProducer.sendEvent(kafkaEventData);
            return true;
        } catch (Exception e) {
            // Rollback occurs here if Kafka fails
            throw new RuntimeException("Failed to sync user with User-Service. Rolling back.");
        }
    }
}
